Vagrant.configure("2") do |config|
  config.trigger.after :destroy do |trigger|
    trigger.name = "Cleanup token e kubeconfig file"
    trigger.run = {inline: "rm -f token kubeconfig"}
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get install -y netcat-openbsd
    echo "192.168.56.110 lotrapanS" | sudo tee /etc/hosts
    echo "192.168.56.111 lotrapanSW" | sudo tee -a /etc/hosts
  SHELL

  config.vm.box = "bento/ubuntu-22.04"

  config.vm.define "lotrapanS" do |master|
    master.vm.hostname = "lotrapanS"
    master.vm.network "private_network", ip: "192.168.56.110"

    master.vm.provision "shell", path: "scripts/k3s_master.sh"

    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end

  config.vm.define "lotrapanSW" do |agent|
    agent.vm.hostname = "lotrapanSW"
    agent.vm.network "private_network", ip: "192.168.56.111"

    agent.vm.provision "shell", path: "scripts/k3s_agent.sh", args: ["192.168.56.110"]

    agent.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end

end
