BOX       = "bento/ubuntu-22.04"
MEMORY    = 1024
CPUS      = 1
MASTER    = "lotrapanS"
WORKER    = "lotrapanSW"
IP_MASTER = "192.168.56.110"
IP_WORKER = "192.168.56.111"

Vagrant.configure("2") do |config|
  config.trigger.after :destroy do |trigger|
    trigger.name = "Cleanup token e kubeconfig file"
    trigger.run = {inline: "rm -f token kubeconfig"}
  end

  config.vm.box = BOX
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y netcat-openbsd
    echo "#{IP_MASTER} #{MASTER}" | tee -a /etc/hosts
    echo "#{IP_WORKER} #{WORKER}" | tee -a /etc/hosts
  SHELL

  config.vm.define MASTER do |master|
    master.vm.hostname = MASTER
    master.vm.network "private_network", ip: IP_MASTER

    master.vm.provision "shell", path: "scripts/k3s_master.sh"

    master.vm.provider "virtualbox" do |vb|
      vb.memory = MEMORY
      vb.cpus = CPUS
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
  end

  config.vm.define WORKER do |agent|
    agent.vm.hostname = WORKER
    agent.vm.network "private_network", ip: IP_WORKER

    agent.vm.provision "shell", path: "scripts/k3s_agent.sh", args: [IP_MASTER, IP_WORKER]

    agent.vm.provider "virtualbox" do |vb|
      vb.memory = MEMORY
      vb.cpus = CPUS
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
  end

end
